// <auto-generated />
using CompanyPro.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyPro.Migrations
{
    [DbContext(typeof(ITIContext))]
    [Migration("20260905082659_v1.1")]
    partial class v11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyPro.Models.DepartmentController", b =>
                {
                    b.Property<int>("Did")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Did"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Did");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Did = 1,
                            Location = "Smart",
                            Name = "SD"
                        },
                        new
                        {
                            Did = 2,
                            Location = "Menofia",
                            Name = "OS"
                        });
                });

            modelBuilder.Entity("CompanyPro.Models.Employee", b =>
                {
                    b.Property<int>("EId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EId = 1,
                            Address = "Cairo",
                            DepartmentId = 1,
                            Name = "Zeniab",
                            Salary = 1000m
                        },
                        new
                        {
                            EId = 2,
                            Address = "Menofia",
                            DepartmentId = 2,
                            Name = "MoEbrahim",
                            Salary = 1000m
                        },
                        new
                        {
                            EId = 3,
                            Address = "Giza",
                            DepartmentId = 1,
                            Name = "Lena",
                            Salary = 1100m
                        });
                });

            modelBuilder.Entity("CompanyPro.Models.Employee", b =>
                {
                    b.HasOne("CompanyPro.Models.DepartmentController", "DepartmentController")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentController");
                });

            modelBuilder.Entity("CompanyPro.Models.DepartmentController", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
